all:
	g++ -g -Wall main.cpp  -o main
	./main

build:
	g++ -g -Wall main.cpp  -o main
run:
	./main
test:
	#./main 100
	#./main 1000
	./main 10000
	./main 20000
	./main 40000
	#./main 80000
	#./main 100000
	#./main 1000000